import {
  AnalysisIcon,
  AssessmentIcon,
  HomeIcon,
  InsightIcon,
  MethodologyIcon,
  OverviewIcon,
  RecommendationIcon,
  RegulatoryIcon,
} from "@/icons";
import {
  markdownContent,
  markdownContent1,
  markdownContent2,
  markdownDescription,
} from "@/mockdata/EMPASectionsMKD";

export const EMPAReportSteps: TStep[] = [
  {
    id: 1,
    title: "home",
    isLocked: false,
    substeps: [],
    icon: HomeIcon,
  },
  {
    id: 2,
    isLocked: false,
    title: "Introduction",
    substeps: [
      {
        id: 1,
        title: "Summary of project",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Summary of project",
      },
      {
        id: 2,
        title: "Executive Summary",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Executive Summary",
      },
    ],
    icon: OverviewIcon,
  },
  {
    id: 3,
    isLocked: false,
    title: "Objective",
    substeps: [
      {
        id: 1,
        title: "Overview of project",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Overview of project",
      },
    ],
    icon: OverviewIcon,
  },
  {
    id: 4,
    isLocked: false,
    title: "methodology",
    substeps: [
      {
        id: 1,
        title: "Data Gathering",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Data Gathering",
      },
      {
        id: 2,
        title: "Standards Screening",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Standards Screening",
      },
      {
        id: 3,
        title: "Project Evaluation",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Project Evaluation",
      },
    ],
    icon: MethodologyIcon,
  },
  {
    id: 5,
    isLocked: false,
    title: "Market analysis",
    substeps: [
      {
        id: 1,
        title: "Market outlook",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Market outlook",
      },
      {
        id: 2,
        title: "Overview of Market pricing",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Overview of Market pricing",
      },
    ],
    icon: AnalysisIcon,
  },
  {
    id: 6,
    title: "Key findings",
    substeps: [
      {
        id: 1,
        title: "EA opportunity overview",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### EA opportunity overview",
      },
      {
        id: 2,
        title: "SDG alignment",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### SDG alignment",
      },
      {
        id: 3,
        title: "Carbon credit market options",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Carbon credit market options",
      },
      {
        id: 4,
        title: "Carbon credit pricing analysis",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Carbon credit pricing analysis",
      },
    ],
    icon: InsightIcon,
    isLocked: false,
  },
  {
    id: 7,
    isLocked: false,
    title: "regulatory",
    substeps: [
      {
        id: 1,
        title: "Regulatory Environment and Market Mechanisms",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,

        markupTitle: "#### Regulatory Environment and Market Mechanisms",
      },
    ],
    icon: RegulatoryIcon,
  },
  {
    id: 8,
    isLocked: false,
    title: "assessment",
    substeps: [
      {
        id: 1,
        title: "Capital Opportunity",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Capital Opportunity",
      },
      {
        id: 2,
        title: "Risk and Opportunities",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Risk and Opportunities",
      },
      {
        id: 3,
        title: "Sustainability",
        isLocked: false,
        data: markdownContent,
        description: markdownDescription,
        markupTitle: "#### Sustainability",
      },
    ],
    icon: AssessmentIcon,
  },
  {
    id: 9,
    isLocked: false,
    title: "recommendation",
    substeps: [
      {
        id: 1,
        title: "Limitations",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Limitations",
      },
      {
        id: 2,
        title: "Action Steps",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Action Steps",
      },
      {
        id: 3,
        title: "Recommendations",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Recommendations",
      },
      {
        id: 4,
        title: "Summary",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Summary",
      },
    ],
    icon: RecommendationIcon,
  },
  {
    id: 10,
    isLocked: false,
    title: "conclusion",
    substeps: [
      {
        id: 1,
        title: "Limitations",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Limitations",
      },
      {
        id: 2,
        title: "Action Steps",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Action Steps",
      },
      {
        id: 3,
        title: "Recommendations",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,
        markupTitle: "#### Recommendations",
      },
      {
        id: 4,
        title: "Summary",
        isLocked: false,
        data: markdownContent2,
        description: markdownDescription,

        markupTitle: "#### Summary",
      },
    ],
    icon: RecommendationIcon,
  },
];
